---
title: "Activity Five for Lab1"
author: "Taehoon Ha"
date: "10/10/2018"
output: 
    github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 1. Matrix and vector multiplication: write a function that will multiply a matrix and a vector (without built-in matrix multiplication function.) A%*%B is not allowed.
```{r}
A <- matrix(1:9, nrow = 3)
b <- c(1, 2, 3)

mat_vect_mult <- function(A, b) {
    p <- dim(A)[1]
    q <- dim(A)[2]
    c <- matrix(0, nrow = p)
    for(i in 1:p) {
        for(j in 1:q) {
            c[i] <- c[i] + A[i, j] * b[j]
        }
    }
    return(c)
}

mat_vect_mult(A, b)
```

We can check our result:
```{r}
A%*%b
```


### 2. Suppose you are betting that you get at least one six in 4 throws of a die. Write a function that simulates one round of the game and prints out whether you win or lose.
```{r}
gambling <- function(){
  bet <- replicate(4, sample(1:6, 1, replace = T))
  result <- sum(bet == 4) >= 1
  ifelse(result, "Win", "Lose")
}

gambling()
```
